name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: paulobritoplht
          password: qwe!123!!
          repository: paulobritoplht/teste:123
          tag_with_ref: false
