name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    env:      
      CAMINHO_PROJETO_WEBAPP: ./TesteGitAction      
      
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: paulobritoplht
          password: qwe!123!!
      -
        name: Build and push
        env:
          IMAGE_TAG: ${{ github.sha }}        
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: paulobritoplht/teste:${{ github.run_number }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -   
        name: Imprimir variaval
        run: echo ${{ github.run_number }}
      -
        name: Build and push latest
        env:
          IMAGE_TAG: ${{ github.sha }}        
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: paulobritoplht/teste:latest      
          
      - name: Build1
        run: dotnet build ${{ env.CAMINHO_PROJETO_WEBAPP }} --configuration Release              
        
